### ISSUE TITLE
Unable to log-in to https://tportal.apexa.ca/auth/partner

### ISSUE THREAD

**Issue by frank-slf** [ApexaCorp/feedback-portal#49] opened 2015-10-22 14:34 UTC
Using carrier5@bluesun.ca credentials.

Using IP 192.26.212.203, where the IP Restrictions are set to 192.26.212.0/24 & 159.208.32.0/19.

Please advise.

**Comment by KelsiElshaw** [comment] 2015-10-22 16:50
Hi Frank,

We believe that we have corrected the issue.
Can you log in again and let us know if the issue persists?

Thank you,


Kelsi Elshaw
Project Manager/Business Analyst

Direct (647) 800-8665
Cell (905) 510-8024

www.apexa.ca


-------- Original message --------

**Comment by frank-slf** [comment] 2015-10-22 17:26
Hi Kelsi,

I still cannot login:
![image](https://cloud.githubusercontent.com/assets/14218407/10672816/5d077682-78c0-11e5-999c-66914a11608c.png)

My current ip is 192.26.212.202

Thanks for looking into this.

Frank

**Comment by mikebrown0** [comment] 2015-10-22 20:10
Hi Frank,

I've removed the IP restriction on your account for the moment.  You set it up correctly, there was just a bug in Milestone 4 that only enforced 1 IP address rather than all of them.  Milestone 4.5 will be deployed in the next 24 hours or so and already contains a fix for this.

-Mike

**Comment by frank-slf** [comment] 2015-11-02 15:44
Hello,

I have just tried to use two IP addresses on APEXA 0.5.1?

Unfortunately it appears I have been locked out gain.

Please help,

Frank

**Comment by KelsiElshaw** [comment] 2015-11-04 01:01
Frank has indicated that this issue still persists in the UAT environment

**Comment by frank-slf** [comment] 2015-11-04 14:06
JFYI 

Sun Life is unable to log into the UAT or test environments at this time.

**Comment by mikebrown0** [comment] 2015-11-05 00:39
Hi Frank,

I can see valid logins for Sunlife users in TRN (training) from today.  All of the passwords for the generic accounts that we issued were changed in TRN due to users stepping on each other's toes during the training event this week.  If you contact one of the users that attended (or Dylan or Kelsi), they should have the credentials to create an account for you in TRN.

I don't have access to the UAT database, but I have a request in to the APEXA IT guys to get access so I can see what's wrong.  I'll let you know once I have access (hopefully tomorrow).

Mike

**Comment by frank-slf** [comment] 2015-11-05 13:27
It is unfortunate that we have lost 3 days of UAT due to the password re-set.

Can someone provide us with carrier access credentials for carrier5?

Thanks,

Frank

**Comment by mikebrown0** [comment] 2015-11-05 18:17
Hi Frank,

APEXA IT has given me access to investigate the problem.  The issue in UAT is not credentials, it's the IP restrictions.  The issue identified previously has been resolved, but it looks like there is an additional issue that is only present in a deployed scenario.  We've identified the problem and it will be resolved in the 0.5.3 release that is currently targeting end-of-day Monday.

In the meantime, I've requested that APEXA IT clear all IP restrictions on your account.  I'll let you know when that has been completed, but I expect it will be completed very shortly.

I apologize for the inconvenience this has caused; this will be the last time IP restrictions cause you an issue.

Mike

**Comment by mikebrown0** [comment] 2015-11-05 18:36
The IP restrictions should be cleared now.  Please try again.

**Comment by frank-slf** [comment] 2015-11-05 18:56
Thank you Mike,

I am now able to log-in.

I will not re-test IP Address restrictions until Tuesday November 10th or when I see v 0.5.3

**Comment by mikebrown0** [comment] 2015-11-11 00:19
Hi Frank,

I just wanted to give you an update on the 0.5.3 release.  We ran into some issues with the final regression tests, so instead of rushing to get it out the door (and cause more issues), I've postponed the release to tomorrow night (Nov 11).

I'll let you know here once it's available.  I apologize for the delay.

Mike

**Comment by mikebrown0** [comment] 2015-11-18 18:26
Hi Frank,

This should now be working correctly.  Let me know if you run into any further issues.

Mike

**Closed by mikebrown0** 2015-11-18 18:26 UTC
Labels: bug

**Comment by frank-slf** [comment] 2015-11-18 18:27
Hi Mike, 

The IP restrictions now work as expected.

Thank you,

Frank
